services:
  homeassistant:
    container_name: ha-skyline-webcams-test
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./custom_components/skylinewebcams:/config/custom_components/skylinewebcams
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8131:8123"
    restart: "no"
